"""suppliers + products

Revision ID: 273f64d236b0
Revises: 80a91b6fd559
Create Date: 2025-10-02 21:25:59.323141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273f64d236b0'
down_revision: Union[str, None] = '80a91b6fd559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vat_default', sa.Enum('IVA_21', 'IVA_19', name='vatrate'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_base', sa.String(length=20), nullable=False),
    sa.Column('factor_per_pack', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('vat_override', sa.Integer(), nullable=True),
    sa.Column('cost_net', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_gross', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_list', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
