"""stock models (warehouse, stock, stock_min)

Revision ID: 980c8de829c6
Revises: 273f64d236b0
Create Date: 2025-10-02 21:32:50.899701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980c8de829c6'
down_revision: Union[str, None] = '273f64d236b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('qty_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uix_stock_product_warehouse')
    )
    op.create_index(op.f('ix_stock_product_id'), 'stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_warehouse_id'), 'stock', ['warehouse_id'], unique=False)
    op.create_table('stock_min',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uix_min_product_warehouse')
    )
    op.create_index(op.f('ix_stock_min_product_id'), 'stock_min', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_min_warehouse_id'), 'stock_min', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_min_warehouse_id'), table_name='stock_min')
    op.drop_index(op.f('ix_stock_min_product_id'), table_name='stock_min')
    op.drop_table('stock_min')
    op.drop_index(op.f('ix_stock_warehouse_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_product_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
