"""purchases + audit logs

Revision ID: b89e08c0379e
Revises: d0b0d3a98aa8
Create Date: 2025-10-03 10:18:17.326072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89e08c0379e'
down_revision: Union[str, None] = 'd0b0d3a98aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
